<?php

namespace Tests\Feature;

use App\Models\Project;
use App\Models\User;
use Illuminate\Support\Facades\Hash;
use Tests\TestCase;

class ProjectControllerTest extends TestCase
{
    public $user;

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->user = User::create([
            'name'          => 'ftp',
            'username'      => 'ftp',
            'email'         => 'ftp@gmail.com',
            'password'      => Hash::make('password'),
            'activated_at'  => now(),
            'office_id'     => 1,
        ]);
    }

    /**
     * A basic feature test example.
     *
     * @return void
     */
    public function test_it_shows_list_of_projects()
    {
        $response = $this
            ->actingAs($this->user)
            ->get(route('projects.index'));

        $response->assertSee('Projects');

        $response->assertStatus(200);
    }

    public function test_it_shows_create_project_form()
    {
        $response = $this
            ->actingAs($this->user)
            ->get(route('projects.create'));

        $response->assertSee('New Program/Project');

        $response->assertStatus(200);
    }

    public function test_it_stores_project()
    {
        $data = Project::factory()->make();

        $this
            ->actingAs($this->user)
            ->post(route('projects.store'), $data);

        $this->assertDatabaseHas('projects', [
            'title' => $data->title,
        ]);
    }
}
